version: "3"

services:
  app:
    build: ./gateway
    ports:
      - "8080:8080"
    networks:
      - mylocal
  mcs1:
    build: ./user
    networks:
      - mylocal
  mcs2:
    build: ./portfolio
    networks:
      - mylocal
  mcs3:
    build: ./cart
    networks:
      - mylocal
networks:
  mylocal:
    external: true